// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnpxkjjnihdvnbghepvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxucHhrampuaWhkdm5iZ2hlcHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDIzNzcsImV4cCI6MjA3MTY3ODM3N30.mkEF-lVM_xlvc_aBB8NWhmWFSteU9JKHsCMVLSMuL9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});